<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('contents')->insert([

            [
                // NO.1
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '1',
                'title' => '真鯛、蓮子鯛10匹',
                'size' => '20-50cm',
                'fishing_area' => '玄界灘',
                'datetime_1' => '2021/09/01 11:11:11',
                'place_1' => 'aa漁港',
                'datetime_2' => '2021/09/01 12:12:12',
                'place_2' => 'bb釣具店',
                'datetime_3' => '2021/09/01 13:13:13',
                'place_3' => 'ccスーパー駐車場',
                'limit' => '2021/09/01 13:00:00',
                'process_1' => '',
                'process_2' => '1',
                'process_3' => '1',
                'process_4' => '',
                'process_5' => '',
                'process_6' => '1',
                'process_7' => '',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '条件に合う方の受け取りをお待ちしています！',
                'is_expired' => '',
                'created_at' => '2021/09/01 10:10:10'
            ],

            [
                // NO.2
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '1',
                'title' => 'ブリ2匹',
                'size' => '50-60cm',
                'fishing_area' => '玄界灘',
                'datetime_1' => '2021/09/01 11:11:11',
                'place_1' => 'aa漁港',
                'datetime_2' => '2021/09/01 12:12:12',
                'place_2' => 'bb釣具店',
                'datetime_3' => '2021/09/01 13:13:13',
                'place_3' => 'ccスーパー駐車場',
                'limit' => '2021/09/01 13:00:00',
                'process_1' => '',
                'process_2' => '1',
                'process_3' => '1',
                'process_4' => '',
                'process_5' => '1',
                'process_6' => '',
                'process_7' => '1',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '小ぶりですが捌きやすいと思います',
                'is_expired' => '',
                'created_at' => '2021/09/01 10:10:10'
            ],

            [
                // NO.3
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '1',
                'title' => 'アジ30匹くらい',
                'size' => '20-50cm',
                'fishing_area' => '玄界灘',
                'datetime_1' => '2021/09/10 11:11:11',
                'place_1' => 'xx漁港',
                'datetime_2' => '2021/09/10 12:12:12',
                'place_2' => 'yy釣具店',
                'datetime_3' => '2021/09/10 13:13:13',
                'place_3' => 'zzスーパー駐車場',
                'limit' => '2021/09/10 13:00:00',
                'process_1' => '',
                'process_2' => '',
                'process_3' => '',
                'process_4' => '1',
                'process_5' => '',
                'process_6' => '',
                'process_7' => '1',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => 'まとめて貰ってくれるかた',
                'is_expired' => '',
                'created_at' => '2021/09/10 10:10:10'
            ],

            [
                // NO.4
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '2',
                'title' => 'ブリ',
                'size' => '50-70cm',
                'fishing_area' => '玄界灘',
                'datetime_1' => '2021/09/15 11:11:11',
                'place_1' => 'aa漁港',
                'datetime_2' => '2021/09/15 12:12:12',
                'place_2' => 'bb釣具店',
                'datetime_3' => '2021/09/15 13:13:13',
                'place_3' => 'ccスーパー駐車場',
                'limit' => '2021/09/15 13:00:00',
                'process_1' => '',
                'process_2' => '1',
                'process_3' => '1',
                'process_4' => '',
                'process_5' => '1',
                'process_6' => '',
                'process_7' => '1',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '一人１本いかがでしょうか？',
                'is_expired' => '',
                'created_at' => '2021/09/15 10:10:10'
            ],

            [
                // No.5
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '2',
                'title' => '太刀魚全部で20本',
                'size' => '指3-5本',
                'fishing_area' => '玄界灘',
                'datetime_1' => '2021/09/10 11:11:11',
                'place_1' => 'oo駅',
                'datetime_2' => '2021/09/10 12:12:12',
                'place_2' => 'ppコンビニ駐車場',
                'datetime_3' => '2021/09/10 13:13:13',
                'place_3' => 'qq公園前',
                'limit' => '2021/09/10 13:00:00',
                'process_1' => '',
                'process_2' => '1',
                'process_3' => '',
                'process_4' => '1',
                'process_5' => '',
                'process_6' => '1',
                'process_7' => '',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '塩焼き美味しいですよ',
                'is_expired' => '',
                'created_at' => '2021/09/10 10:10:10'
            ],

            [
                // NO.6
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '2',
                'title' => 'イトヨリ10匹',
                'size' => '20-40cm',
                'fishing_area' => '対馬周辺',
                'datetime_1' => '2021/09/10 11:11:11',
                'place_1' => 'dee漁港',
                'datetime_2' => '2021/09/10 12:12:12',
                'place_2' => 'bee釣具店',
                'datetime_3' => '2021/09/10 13:13:13',
                'place_3' => 'ceeスーパー駐車場',
                'limit' => '2021/09/01 13:00:00',
                'process_1' => '',
                'process_2' => '1',
                'process_3' => '1',
                'process_4' => '',
                'process_5' => '',
                'process_6' => '1',
                'process_7' => '',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => 'その他条件、ご相談ください',
                'is_expired' => '',
                'created_at' => '2021/09/01 10:10:10'
            ],

            [
                // NO.7
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '3',
                'title' => 'アコウ8匹',
                'size' => '20-30cm',
                'fishing_area' => '',
                'datetime_1' => '2021/09/11 11:11:11',
                'place_1' => 'apple漁港',
                'datetime_2' => '2021/09/11 12:12:12',
                'place_2' => 'peach釣具店',
                'datetime_3' => '2021/09/11 13:13:13',
                'place_3' => 'bananaスーパー駐車場',
                'limit' => '2021/09/11 13:00:00',
                'process_1' => '',
                'process_2' => '1',
                'process_3' => '1',
                'process_4' => '',
                'process_5' => '',
                'process_6' => '1',
                'process_7' => '',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '冷凍でよければ期限後も受け付けます',
                'is_expired' => '',
                'created_at' => '2021/09/11 10:10:10'
            ],

            [
                // NO.8
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '3',
                'title' => '真鯛、蓮子鯛10匹',
                'size' => '20-50cm',
                'fishing_area' => '鹿児島',
                'datetime_1' => '2021/09/12 11:11:11',
                'place_1' => 'super漁港',
                'datetime_2' => '2021/09/12 12:12:12',
                'place_2' => 'big釣具店',
                'datetime_3' => '2021/09/12 13:13:13',
                'place_3' => 'okスーパー駐車場',
                'limit' => '2021/09/12 13:00:00',
                'process_1' => '1',
                'process_2' => '',
                'process_3' => '',
                'process_4' => '',
                'process_5' => '',
                'process_6' => '1',
                'process_7' => '',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '条件に合う方の受け取りをお待ちしています！',
                'is_expired' => '',
                'created_at' => '2021/09/12 10:10:10'
            ],

            [
                // NO.9
                'file_name' => '',
                'file_path' => '',
                'created_user_id' => '4',
                'title' => 'ブリ5匹',
                'size' => '50-70cm',
                'fishing_area' => '鹿児島',
                'datetime_1' => '2021/09/13 11:11:11',
                'place_1' => 'where漁港',
                'datetime_2' => '2021/09/13 12:12:12',
                'place_2' => 'grape釣具店',
                'datetime_3' => '2021/09/13 13:13:13',
                'place_3' => 'nonoスーパー駐車場',
                'limit' => '2021/09/14 13:00:00',
                'process_1' => '1',
                'process_2' => '',
                'process_3' => '',
                'process_4' => '',
                'process_5' => '',
                'process_6' => '1',
                'process_7' => '',
                'process_8' => '',
                'process_9' => '',
                'process_10' => '',
                'cool_now' => '1',
                'cool_give' => '1',
                'content' => '条件に合う方の受け取りをお待ちしています！',
                'is_expired' => '',
                'created_at' => '2021/09/13 10:10:10'
            ],


        ]);
    }
}
